<Project>
	<Import Project="ArchiSteamFarm/Directory.Build.props" />

	<PropertyGroup>
		<PluginName>FreeLicenseCleaner</PluginName>
		<Version>1.0.0.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<ApplicationIcon />
		<Authors>satan007</Authors>
		<Company>$(Authors)</Company>
		<Copyright>Copyright © $([System.DateTime]::UtcNow.Year) $(Company)</Copyright>
		<Description>ArchiSteamFarm plugin: automatically finds and removes free ("on demand") Steam licenses one at a time.</Description>
		<PackageIcon />
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/$(Company)/ASF-FreeLicenseCleaner</PackageProjectUrl>
		<PackageReleaseNotes>$(PackageProjectUrl)/releases</PackageReleaseNotes>
		<RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
	</PropertyGroup>

	<!-- Reset ASF signing settings, as we don't sign this plugin -->
	<PropertyGroup>
		<AssemblyOriginatorKeyFile />
		<PublicSign>false</PublicSign>
		<SignAssembly>false</SignAssembly>
	</PropertyGroup>
</Project>
